create sequence notification_sequence start with 1 increment by 1;
create table notification_request (priority integer, id bigint not null, channel varchar(255) not null, destinations varchar(255) not null, source varchar(255) not null, text varchar(255), primary key (id));
create sequence notification_sequence start with 1 increment by 1;
create table notification_request (priority integer, id bigint not null, channel varchar(255) not null, destinations varchar(255) not null, source varchar(255) not null, text varchar(255), primary key (id));
create sequence notification_sequence start with 1 increment by 1;
create table notification_request (priority integer, id bigint not null, channel varchar(255) not null, destinations varchar(255) not null, source varchar(255) not null, text varchar(255), primary key (id));
create sequence notification_sequence start with 1 increment by 1;
create table notification_request (priority integer, id bigint not null, channel varchar(255) not null, destinations varchar(255) not null, source varchar(255) not null, text varchar(255), primary key (id));
create sequence notification_sequence start with 1 increment by 1;
create table notification_request (priority integer, id bigint not null, channel varchar(255) not null, destinations varchar(255) not null, source varchar(255) not null, text varchar(255), primary key (id));
create sequence notification_sequence start with 1 increment by 1;
create table notification_request (priority integer, id bigint not null, channel varchar(255) not null, destinations varchar(255) not null, source varchar(255) not null, text varchar(255), primary key (id));
create sequence notification_sequence start with 1 increment by 1;
create table notification_request (priority integer, id bigint not null, channel varchar(255) not null, destinations varchar(255) not null, source varchar(255) not null, text varchar(255), primary key (id));
create sequence notification_sequence start with 1 increment by 1;
create table notification_request (priority integer, id bigint not null, channel varchar(255) not null, destinations varchar(255) not null, source varchar(255) not null, text varchar(255), primary key (id));
create sequence notification_sequence start with 1 increment by 1;
create table notification_request (priority integer, id bigint not null, channel varchar(255) not null, destinations varchar(255) not null, source varchar(255) not null, text varchar(255), primary key (id));
create sequence notification_sequence start with 1 increment by 1;
create table notification_request (priority integer, id bigint not null, channel varchar(255) not null, destinations varchar(255) not null, source varchar(255) not null, text varchar(255), primary key (id));
create sequence notification_sequence start with 1 increment by 1;
create table notification_request (priority integer, id bigint not null, channel varchar(255) not null, destinations varchar(255) not null, source varchar(255) not null, text varchar(255), primary key (id));
